Provide facility to test at runtime if an architecture is supported
xtensor-stack/xsimd pull request #471
Opened 2021-05-11 23:30 UTC by serge-sans-paille

2021-05-12 18:23 UTC, serge-sans-paille commented
Green, at last. I should probably rename `visit` into `map` and provide a `fold` operator of sort.

2021-05-16 08:39 UTC, wolfv commented
This is going to be really useful for mamba :)

2021-05-16 17:19 UTC, serge-sans-paille commented
> This is going to be really useful for mamba :)

Nice! Why?

2021-05-18 08:57 UTC, JohanMabille requested changes
Nitpicking: 4 spaces indent and opening curly braces go on a new line.

2021-05-18 08:57 UTC, JohanMabille commented on include/xsimd/config/xsimd_arch.hpp
> +          static void visit(F&& f) {
I think `map`, or `for_each` would be a better name.

2021-05-18 08:57 UTC, JohanMabille commented on include/xsimd/config/xsimd_instruction_set.hpp
> +    ((((major) % 100u) * 10000000u) + (((minor) % 100u) * 100000u) + ((patch) % 100000u))
I don't understand why you use `unsigned int`here while you changed form `unsigned` to `int` in the different structures modeling the supported architectures.

2021-05-18 20:39 UTC, serge-sans-paille commented
@JohanMabille should be good now. I switched version to unsigned because it's easier to reason on unsigned, and there's no value in signed version anyway (?)

2021-05-19 14:53 UTC, JohanMabille commented
Indeed, maybe I mixed things or read a single commit diff instead of the whole changes.

2021-05-19 14:53 UTC, JohanMabille approved these changes

2021-05-19 14:53 UTC, merged

2021-05-21 06:51 UTC, guyuqi commented
It failed to build on:
`Arm64 gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0` :

```
/home/yuqi/xsimd/include/xsimd/memory/../config/xsimd_arch.hpp:502:77:   required from ‘decltype (((xsimd::arch::detail::dispatcher<F, ArchList>*)this)->xsimd::arch::detail::dispatcher<F, ArchList>::functor(xsimd::arch::default_{}, (forward<Tys>)(xsimd::arch::detail::dispatcher::operator()::args)...)) xsimd::arch::detail::dispatcher<F, ArchList>::operator()(Tys&& ...) [with Tys = {unsigned int (&)[17], int}; F = sum; ArchList = xsimd::arch::arch_list<xsimd::arch::neon64, xsimd::arch::neon>; decltype (((xsimd::arch::detail::dispatcher<F, ArchList>*)this)->xsimd::arch::detail::dispatcher<F, ArchList>::functor(xsimd::arch::default_{}, (forward<Tys>)(xsimd::arch::detail::dispatcher::operator()::args)...)) = unsigned int]’
/home/yuqi/xsimd/test/test_arch.cpp:72:39:   required from here
/home/yuqi/xsimd/test/test_arch.cpp:53:11: error: ‘batch acc’ has incomplete type
   53 |     batch acc(static_cast<T>(0));
      |           ^~~
/home/yuqi/xsimd/test/test_arch.cpp:54:29: error: incomplete type ‘batch’ {aka ‘xsimd::batch<unsigned int, 16>’} used in nested name specifier
   54 |     const unsigned n = size / batch::size * batch::size;
      |                        ~~~~~^~~~~~~~~~~~~
/home/yuqi/xsimd/test/test_arch.cpp:54:43: error: incomplete type ‘batch’ {aka ‘xsimd::batch<unsigned int, 16>’} used in nested name specifier
   54 |     const unsigned n = size / batch::size * batch::size;
      |                        ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
/home/yuqi/xsimd/test/test_arch.cpp:55:35: error: incomplete type ‘batch’ {aka ‘xsimd::batch<unsigned int, 16>’} used in nested name specifier
   55 |     for(unsigned i = 0; i != n; i += batch::size)
      |                                 ~~^~~~~~~~~~~~~~
/home/yuqi/xsimd/test/test_arch.cpp:56:16: error: invalid use of incomplete type ‘using batch = xsimd::arch::batch<unsigned int, xsimd::arch::neon64>’ {aka ‘class xsimd::batch<unsigned int, 16>’}
   56 |         acc += batch(data + i);
      |                ^~~~~~~~~~~~~~~
In file included from /home/yuqi/xsimd/include/xsimd/memory/../config/xsimd_align.hpp:15,
                 from /home/yuqi/xsimd/include/xsimd/memory/xsimd_alignment.hpp:14,
                 from /home/yuqi/xsimd/include/xsimd/xsimd.hpp:14,
                 from /home/yuqi/xsimd/test/test_utils.hpp:20,
                 from /home/yuqi/xsimd/test/test_arch.cpp:14:
/home/yuqi/xsimd/include/xsimd/memory/../config/xsimd_arch.hpp:42:11: note: declaration of ‘using batch = xsimd::arch::batch<unsigned int, xsimd::arch::neon64>’ {aka ‘class xsimd::batch<unsigned int, 16>’}
   42 |     class batch;
      |           ^~~~~

```
@serge-sans-paille @JohanMabille