Add xsimd::polar()
xtensor-stack/xsimd pull request #739
Opened 2022-05-12 21:45 UTC by jatinchowdhury18

Intended to be the equivalent of `std::polar()`

2022-05-16 20:11 UTC, serge-sans-paille requested changes
Thanks for the contribution! I have one major concern considering the API, but that's trivial to fix.

2022-05-16 20:11 UTC, serge-sans-paille commented on include/xsimd/arch/generic/xsimd_generic_math.hpp
> +        inline batch<std::complex<T>, A> polar(const batch<T, A>& theta, requires_arch<generic>) noexcept
shouldn't this be `r` instead of `theta`?

2022-05-16 20:11 UTC, serge-sans-paille commented on include/xsimd/arch/generic/xsimd_generic_math.hpp
> +        inline batch<std::complex<T>, A> polar(const batch<T, A>& theta, requires_arch<generic>) noexcept
And then the formula is different, of course. But that would match the C++ api, as https://en.cppreference.com/w/cpp/numeric/complex/polar

2022-05-16 20:11 UTC, serge-sans-paille commented on include/xsimd/types/xsimd_api.hpp
> +     * @return exp(i * \c theta).
This is not the standard API, we try to stick to `std::polar`, even if that misses an optimization

2022-05-17 10:05 UTC, jatinchowdhury18 commented
Ah, good call, I hadn't realized that my "phase-only" implementation was not part of the standard library. I've removed the phase-only implementation, and tweaked the default arguments of the other implementation to match the standard API.

2022-05-18 05:31 UTC, merged

2022-05-18 05:31 UTC, serge-sans-paille commented
Thanks for this patch o/