Provide generic signed /unsigned type conversion
xtensor-stack/xsimd pull request #905
Opened 2023-03-04 22:13 UTC by serge-sans-paille

A reinterpret_cast is usually the way to go. For the range of value when it's valid in C, we achieve the same behavior for batches.

Fix #735

2023-03-07 14:21 UTC, JohanMabille requested changes

2023-03-07 14:21 UTC, JohanMabille commented on include/xsimd/arch/generic/xsimd_generic_details.hpp
> +            inline batch<uint64_t, A> fast_cast(batch<uint64_t, A> const& self, batch<int64_t, A> const&, requires_arch<generic>) noexcept
Looks like you inverted the arguments here.

2023-03-07 14:21 UTC, JohanMabille commented on include/xsimd/arch/generic/xsimd_generic_details.hpp
> +                return bitwise_cast<int64_t>(self);
This should bitwise cast to `uint64_t`

2023-03-07 14:29 UTC, JohanMabille commented on include/xsimd/arch/generic/xsimd_generic_details.hpp
> +            inline batch<uint64_t, A> fast_cast(batch<uint64_t, A> const& self, batch<int64_t, A> const&, requires_arch<generic>) noexcept
(But then I wonder why the tests are passing in the build where we force not instruction set)

2023-03-07 20:42 UTC, JohanMabille commented on include/xsimd/arch/generic/xsimd_generic_details.hpp
> +            inline batch<uint64_t, A> fast_cast(batch<uint64_t, A> const& self, batch<int64_t, A> const&, requires_arch<generic>) noexcept
This one is not fixed in your latest commit

2023-03-07 21:33 UTC, serge-sans-paille commented
It now is ;-)

2023-03-08 08:05 UTC, JohanMabille approved these changes

2023-03-08 08:05 UTC, JohanMabille commented
The fialure is unrelated to the changes.

2023-03-08 08:05 UTC, merged