Feature/rotate
xtensor-stack/xsimd pull request #933
Opened 2023-06-01 05:26 UTC by serge-sans-paille

2023-06-01 05:52 UTC, serge-sans-paille commented
Still need to specialize the neon version of `rotate_left` / `rotate_right`.
I haven't checked SVE yet.

2023-06-02 05:33 UTC, serge-sans-paille commented
cc @JohanMabille ready for review, I'm pretty happy about that one!

2023-06-07 12:21 UTC, JohanMabille requested changes
Except the names mismatch, looks good to me, thanks for this implementation!

2023-06-08 06:02 UTC, JohanMabille approved these changes

2023-06-08 06:02 UTC, merged